defaults: &defaults
  adapter: postgresql
  encoding: unicode
  pool: 5

test:
  database: zencodeit_test
  <<: *defaults

development:
  database: zencodeit_development
  <<: *defaults

production:
  database: zencodeit_production
  <<: *defaults
